############# English navigation ##############

[[main]]
name = "People"
url = "/people"
weight = 1

[[main]]
name = "Research"
url = "/research"
weight = 2

[[main]]
name = "Datasets"
url = "/datasets"
weight = 3

# [[main]]
# name = "Sponsors"
# url = "/sponsors"
# weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 6
